README.md
Update readme, test branching and merge requests
=> Ifu 1234556 test

src/components/article/Article.jsx, styles/base.css, styles/components.footer.css, tailwind.config.js
fix hero image overflow bug, remove scrollbar styles for now
=> fix hero image overflow bug, remove scrollbar styles for now

package.json, pages/_app.js, src/components/layout/Layout.jsx, yarn.lock
add nprogress page load indicator
=> add nprogress page load indicator

pages/404.jsx, pages/_document.jsx
=> fix missing env variable bug

pages/hae.jsx, test/pages/error500.test.jsx
=> adjust search highlight color

package.json, pages/[theme]/[...path].jsx, src/components/article/Article.jsx, src/components/article/ContentMapper.jsx, src/components/article/ReadMoreBlock.jsx, src/components/layout/Layout.jsx, src/lib/content-utils.js, src/lib/ssr-api.js, src/page-templates/ArticlePage.jsx, styles/components.article.css, test/pages/__snapshots__/error500.test.jsx.snap, yarn.lock
- add drupal JSON api params builder
- run common content and page content request in parallel. They don't have any relations so no need to wait for one or other.
- add hero image from drupal API
- move content resolvers to server side.
=> add real links to  readmore blocks, add hero

Dockerfile
current DRUPAL_SITE_ID in azure pipeline env is not correct. test build using all but SITE_ID and _SECRET vars from Azure env
=> test all env vars except drupal_site id(old) and secrets

.env.production, Dockerfile, next.config.js, pages/_app.js, src/lib/ssr-api.js
test if update prerendering works in Azure without next-user
=> test if build runs in Azure without using next-user

Dockerfile, next.config.js, pages/[...slug].jsx, src/components/feedback/FeedbackForm.jsx, src/lib/ssr-api.js
test scope of env variables throughout the CI/CD pipeline
=> test scope of env variables throughout the CI/CD pipeline

.env.production, Dockerfile, next.config.js, pages/[...slug].jsx, src/lib/ssr-api.js, src/page-templates/ArticlePage.jsx
log build and render separately
=> test build and render separately

Dockerfile, src/lib/ssr-api.js
test Dockerfile ARGs. better error logging in page generation
=> test Dockerfile ARGs. better error logging in page generation

Dockerfile
- Test buildArgs directly from build-config.yml in azure.
- remove ARG defaults from Dockerfile builder
=> Test buildArgs directly from build-config.yml in azure

Dockerfile
=> Revert Dockerfile test

src/lib/query-params.js
fetch readmore-links in accordion blocks
=> fetch readmore-links in accordions

pages/cookie-settings.jsx, src/components/layout/Layout.jsx, src/components/layout/TopMenu.jsx, src/page-templates/AboutPage.jsx
- render CityMenu only if there are cities loaded
=> disable CityMenu if there are no municipalities

public/locales/fi/common.json
remove debug line from dictionary file
=> remove debug line from dictionary file

Dockerfile, pages/[...slug].jsx, src/components/article/ReadMoreBlock.jsx
Remove lingering target="_blank" attribute
=> remove target:_blank from linkblock main link

Dockerfile
=> remove unused file copy from docker build process

pages/api/available-locales.js, pages/api/feedback.js, pages/api/localinfo.js, pages/api/search/[locale].js, pages/search.jsx, src/components/feedback/FeedbackForm.jsx, src/components/feedback/InfoBlock.jsx, src/components/feedback/SubmitLoader.jsx, src/components/search/LanguageFilters.jsx, src/components/search/SearchBar.jsx, src/lib/elasticsearch.js, src/lib/query-params.js, src/store.js
- Feedback form connected to drupal webform
=> connect feedback form to drupal webform

src/hooks/useAnalytics.js, src/lib/elasticsearch.js
testing elasticsearch without SSL
=> testing elasticsearch without SSL

src/hooks/useAnalytics.js, src/lib/ssr-api.js
debugging NEXT_PUBLIC_DRUPA_BASE_URL in resolvePath
=> debugging NEXT_PUBLIC_DRUPA_BASE_URL in resolvePath

src/components/languages/LanguageSelector.jsx
remove language version prefetch
=> remove lang prefetching

.gitignore, Dockerfile, logger.js, package.json, yarn.lock
- remove events.log file. Gets too big too soon. STDOUT will do.
- rotate error log per day.
=> add log file rotation

.gitignore, Dockerfile, logger.js, logs/README.md, src/lib/ssr-api.js
- addbug/toomuch-logging-in-build
=> add logs folder to git for Docker container

pages/404.jsx, pages/[[...slug]].jsx, pages/_app.js, pages/search.jsx, pages/sitemap.jsx, src/components/article/ContentMapper.jsx, src/components/article/VideoBlock.jsx, src/components/layout/CookieConsent.jsx, src/components/layout/Drawer.jsx, src/components/layout/FooterLinks.jsx, src/components/layout/Layout.jsx, src/components/layout/TopMenu.jsx, src/components/navi/AboutMenu.jsx, src/components/navi/MainMenu.jsx, src/components/navi/Menu.jsx, src/components/navi/MenuGroup.jsx, src/components/navi/MobileNavi.jsx, src/components/navi/SubMenu.jsx, src/components/search/TopSearch.jsx, src/lib/cacher/menu-cache.js, src/lib/cacher/page-cache.js, src/lib/ssr-api.js, src/page-templates/AboutPage.jsx, src/page-templates/ArticlePage.jsx, src/page-templates/HomePage.jsx, styles/base.css, styles/components.mainmenu.css
- set dynamic imports to browser only.
- menu ssr render bug fix
-
=> set dynamic imports to ssr:false to fix ssr mismatch errors

pages/[[...slug]].jsx
node id  redirection separated from old path redirects
=> better path alias redirection block

src/components/layout/CommonHead.jsx, styles/components.mainmenu.css
- remove trailing slash from og:url
- print out og:image only if page has image
=> Ifu 728 preview 404

google012bbfdb5a0b9dba.html
add google domain verification html file
=> add google domain verification file

src/hooks/useAnalytics.js
* added requireCookieConsent
* Updated analytics behaviour when disabled
* Refactored analytics code when disabled
* Refactored analytics code when disabled
* Refactored analytics code when disabled
* testing - removed disableCookies
* Reverted disableCookies change
* Enable cookies
* Updated tracking
* Analytics changes
* formated code
* Changes
Co-authored-by: Vitals9367 <vitalijus.alsauskas@ibm.com>
=> Feature/ifu 811 (#202)

pages/404.jsx
Added missing translation to 404 page.
=> 404-page help text for Ukraine

next.config.js
add another image domain to next.config.
=> add another image domain to next.config.

pages/sitemap.jsx, src/lib/ssr-api.js
To test: Go to the sitetmap (linked in the footer menu) and try switching the languages around. Note that if you see a menu item in Finnish when you are on another language, it means that menu item hasn't been tranlated.
=> IFU-837 - Got sitemap to translate in a roundabout fashion

.env.example.local
- https://github.com/City-of-Helsinki/drupal-infofinland/pull/258
=> UHF-9624: hardcode local secrets

pages/api/feedback.js
https://github.com/City-of-Helsinki/drupal-infofinland/pull/315
=> UHF-10062: Submit forms to webform with id infofinland_contact

src/components/feedback/FeedbackForm.jsx
Fixes feedback form.
- Run `make fresh` on backend
- `nvm use; npm install -g yarn; yarn; yarn run dev`
[UHF-9773]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UFH-X: Fix feedback form

src/components/layout/Layout.jsx, src/hooks/useAddAskem.js, src/page-templates/ArticlePage.jsx, styles/components.article.css
Fixed the reset, moved the block to correct place, disabled FA and fonts
=> UHF-10876 minor tweaks and fixes to askem block

.github/workflows/test.yml, src/__mocks__/@sentry/nextjs.ts, test/src/components/article/__snapshots__/VideoBlock.test.jsx.snap
Fix `yarn test`, run tests on CI.
- Run `nvm use; npm install -g yarn`
- Run `yarn install`
=> UHF-X: Fix tests - mock sentry library

styles/components.askem.css
- Run `make fresh` on backend
- Run `nvm use; npm install -g yarn`
- Run `yarn build; yarn start` (prefetching is disabled on `yarn run dev`)
[UHF-11043]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11043: Add additional visual fixes for the Askem block

.github/workflows/test.yml, package.json, sonar-project.properties
Enabled sonarcloud.
[UHF-11832]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11832: Enable sonarcloud
